[project]
name = "lab3-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "l-rivat-ece", email = "lucien.rivat@edu.ece.fr" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
lab3-1 = "lab3_1:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
